apiVersion: v2
name: neptune-docs
version: 2.0.0
description: Neptune docs
maintainers: # (optional)
  - name: Neptune
    email: contact@neptune.ai
    url: https://neptune.ai
engine: gotpl
appVersion: 2.8.18
type: application
icon: https://ui.neptune.ai/api/static/neptune-ai-logo-blue-vertical.png
dependencies: []