{{ if (gt (int .Values.docs.replicas) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "chart.fullname" . }}-docs
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "chart.name" . }}
      release: {{ .Release.Name }}
      component: docs
{{ end }}